# adapted from https://www.honeybadger.io/blog/flask-github-actions-continuous-delivery/
name: run-unit-tests

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  
      - uses: actions/setup-python@v2  
      - run: pip install flask
      - run: pip install pytest
      - run: pytest
